sources:
  adiga:
    name: "Adiga University Portal"
    url: "https://www.adiga.kr"
    enabled: true
    desktop_path: "/man/inf/mainView.do?menuId=PCMANINF1000"
    mobile_url: "https://m.adiga.kr"
    selectors:
      article_links: ['a[onclick*=\"fnDetailPopup\"]']
      content: ['.content', '.article-content', '.board-view']
